[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  MONGODB_URI = "mongodb+srv://cours-test:7dtfj2xgKJXFLd1E@bouderga.el84tpe.mongodb.net/test_mongo?retryWrites=true&w=majority"

[context.split1]
  command = "npm run build"
  publish = "dist"
